# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: azure_outbound

# label should be a human readable label that conveys what this skillet will do
label: Outbound on Azure

# description is a longer more informative version of a label
description: Using VM-Series to provide Outbound protection on Azure

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  collection:
    - YKB Skillets
  terraform_provider: azurerm


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
  - name: location
    description: Azure Region to Setup Demo
    default: southeastasia
    type_hint: text
  - name: resource_group_name
    description: Rresource Group of the Demo
    default: skillet-azure-outbound-rg
    type_hint: text
  - name: customdata
    description: Custom Data Field for Bootstrap. Format is "storage-account=<Storage Account Name>,access-key=<Access Key>,file-share=<Azure File Share Name>,share-directory=None"
    default:
    type_hint: text
  - name: adminUsername
    description: Username to access VM-Series and Ubuntu VM
    default: paloalto
    type_hint: text
  - name: adminPassword
    description: Password to access VM-Series and Ubuntu VM
    default:
    type_hint: password
  