# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: alicloud_single_pavm

# label should be a human readable label that conveys what this skillet will do
label: Alicloud Single Pan-OS VM-Series

# description is a longer more informative version of a label
description: Alicloud Single Pan-OS VM-Series

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  collection:
    - YKB Skillets
  terraform_provider: alicloud


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
  - name: access_key
    description: Alicloud Access Key
    default: access_key
    type_hint: text
  - name: secret_key
    description: Alicloud Secret Key
    default:
    type_hint: password
  - name: fw-region
    description: Alicloud Region
    default: ap-southeast-1
    type_hint: text
  - name: fw-vpc
    description: VPC Name
    default: FW-VPC
    type_hint: text
  - name: fw-vpc-cidr
    description: VPC CIDR
    default: 10.88.0.0/16
    type_hint: text
  - name: fw-vswitch-mgmt-cidr
    description: Mgmt Subnet
    default: 10.88.0.0/24
    type_hint: text
  - name: fw-vswitch-untrust-cidr
    description: Untrust Subnet
    default: 10.88.1.0/24
    type_hint: text
  - name: fw-vswitch-trust-cidr
    description: Trust Subnet
    default: 10.88.2.0/24
    type_hint: text
  - name: instance-type
    description: Instance Type
    default: ecs.sn2ne.xlarge
    type_hint: text
  - name: instance-name
    description: Name of the Instance
    default: FW-VM
    type_hint: text
  - name: MGMT-IP
    description: Mgmt Interface IP
    default: 10.88.0.8
    type_hint: text
  - name: UNTRUST-IP
    description: Untrust Interface IP
    default: 10.88.1.8
    type_hint: text
  - name: TRUST-IP
    description: Trust Interface IP
    default: 10.88.2.8
    type_hint: text
